spring.application.name=biblioteca
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Biblioteca

spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update