spring.application.name=biblioteca
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Biblioteca

spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jricken@faeterj-petropolis.edu.br
#  https://myaccount.google.com/apppasswords 
spring.mail.password=iccl ehzf nlng dbax
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

api.security.token.secret=${JWT_SECRET:@vou-ser-um-profissional-de-cyberseguranca-401}